### ISSUE TITLE
How to test reducers that use `handle`?

### ISSUE THREAD

**Issue by randycoulman** [lelandrichardson/redux-pack#19]
I love the idea behind this library and am tempted to adopt it, but I don't see a good way to test reducers that use `handle`.

With thunk or other promise middleware, I can dispatch a manually created action with a type of `LOAD_FOO_STARTED` or `LOAD_FOO_FAILED` and test against that.  But here, the structure of the action is an internal implementation detail that I can't get at from my tests.

Any thoughts on how to achieve this?

One idea is to extract the functions that create the various actions and expose them for use in tests.

Something like:
```js
function makeStartAction({ type, payload, meta }) {
  return {
    type,
    payload,
    meta: {
      ...meta,
      [KEY.LIFECYCLE]: LIFECYCLE.START,
      [KEY.TRANSACTION]: transactionId,
    },
  }
}
```

etc.

It looks like `KEY` and `LIFECYCLE` are public exports of the package, so I could make my own utilities that do this, but that seems hard to maintain.

**Comment by lelandrichardson** [comment]
@randycoulman yes, currently the suggested way to do this would be to use `KEY.LIFECYCLE` like you mentioned.

I would be open to considering exporting some utility functions like this, but I also don't want to increase the surface area of the library too much.

**Comment by randycoulman** [comment]
OK, thanks.  I'll play with it a bit as-is and then decide if I want to submit a PR.  I really like the look of this library, so I'm excited to give it a try.  Thanks for releasing it!
