### ISSUE TITLE
Question: `.then(success, failure)` vs `.then(success).catch(failure)`

### ISSUE THREAD

**Issue by saltycrane** [lelandrichardson/redux-pack#23]
I saw [your comment here][1]:

```
  // NOTE(lmr):
  // it's debatable whether or not we want `.then(success, failure)`
  // versus `.then(success).catch(failure)`
```

and am curious about it because I recently made a [change to our code][2]. What are the downsides of using `.then(success, failure)`?

[1]: https://github.com/lelandrichardson/redux-pack/blob/585d5b8edefcf5802d9b2d1371a3ff4d6706a7ec/src/middleware.js#L72-L74
[2]: https://github.com/TrueCar/gluestick/issues/354

**Comment by lelandrichardson** [comment]
@saltycrane there is really only one difference between the two.  If we have:

```
const p = doSomething().then(success).catch(failure).catch(() => console.log('error!'));
```
and
```
const p = doSomething().then(success, failure).catch(() => console.log('error!'));
```

The only way `error!` will get logged in the former case is if the `failure` function throws an error.  In the latter case, we will see `error!` if *either* of the `success` or `failure` methods throw an error.

I came to the conclusion that the latter case is what we would want for `redux-pack`. An error in either case would mean a reducer threw an error, or a connected react component re-rendering for instance. I think the symmetric behavior here is desired.

**Comment by saltycrane** [comment]
Thank you for your response!

`.then(success, failure)` makes sense to me also.

`redux-pack` looks great-- helpful information in the `README` also!
