### ISSUE TITLE
Failed to compile project when importing redux-pack

### ISSUE THREAD

**Issue by AM-NiceDay** [lelandrichardson/redux-pack#24]
Node version: v7.2.0
Project created via create-react-app with react-scripts v0.7.0

I've tried to install with both `npm install -S redux-pack` and `yarn add redux-pack`, but when I'm importing redux-pack into project:
```import { middleware as reduxPackMiddleware } from 'redux-pack';```

I'm receiving this error:
```
Failed to compile.

Error in ./~/redux-pack/lib/handle.js
Module not found: 'deline' in [path to project]/node_modules/redux-pack/lib

 @ ./~/redux-pack/lib/handle.js 1:1303-1320
```

I've already tried manually install 'deline' module and it appears in 'node_modules' folder, but haven't succeed.

Can someone please share any thoughts on possible solutions and I will try to fix it?

**Comment by kMeillet** [comment]
https://github.com/airbnb/deline/issues/1

It seem "Deline" package have an incorrect main entrypoint in package.json file.

You can change it in "node_modules/deline/package.json".

I think Airbnb will resolve the problem asap.

If you use WebPack, just use "safe-deline" package : https://github.com/kMeillet/safe-deline and add module aliasing :) .

**Comment by casio** [comment]
Hey guys,

appears I have a possibly related similar issue - after installing & importing `redux-pack` I get:
```
TransformError: <project>/node_modules/deline/build/deline.js: Couldn't find preset "airbnb" relative to directory "<project>/node_modules/deline"
```

Installing `babel-preset-airbnb` works around this for me, but I thought I let you know anyway.
