### ISSUE TITLE
Inconsistent usage of state and action variables in handler

### ISSUE THREAD

**Issue by AM-NiceDay** [lelandrichardson/redux-pack#27]
At first thank you for your work I really like the interface you've built to handle actions in reducers.

I have a proposal to improve it. Here is an example of handler usage:
```
// reducer.js
import { handle } from 'redux-pack';

export function fooReducer(state = initialState, action) {
  const { type, payload } = action;
  switch (type) {
    case LOAD_FOO:
      return handle(state, action, {
        start: s => ({
          ...s,
          isLoading: true,
          fooError: null
        }),
        finish: s => ({ ...s, isLoading: false }),
        failure: s => ({ ...s, fooError: payload }),
        success: s => ({ ...s, foo: payload }),
      });
    default:
      return state;
  }
}
```

Here state is provided as handler parameter and action is taken from closure. I think the usage of this variables should be consistent either via handler params or from closure.

1) Handler params:
```
...
success: (s, a) => ({ ...s, foo: a.payload }),
...
```

2) Closure:
```
reducer(state = initialState, action) {
  ...
  success: () => ({ ...state, foo: action.payload }),
}
```

I like first variant more for a few reasons:
1) It doesn't break current api.
2) We will be able to extract handler functions and reuse across one or more reducers.

Please let me know about your opinion and I will create a pull request with the change.

**Comment by lelandrichardson** [comment]
Merged and available in 0.1.4
