### ISSUE TITLE
Question about multiple dispatches / renders

### ISSUE THREAD

**Issue by saltycrane** [lelandrichardson/redux-pack#31]
> This can be problematic because we are treating several dispatches as all part of a single transaction, but in reality, each dispatch causes a separate rerender of the entire component tree, where we not only pay a huge performance penalty, but also risk the redux store being in an inconsistent state.

I see redux-pack does 3 dispatches in the middleware
https://github.com/lelandrichardson/redux-pack/blob/master/src/middleware.js#L28
https://github.com/lelandrichardson/redux-pack/blob/master/src/middleware.js#L40
https://github.com/lelandrichardson/redux-pack/blob/master/src/middleware.js#L55

I don't understand why redux-pack will not cause separate rerenders for each lifecycle stage (start, success, failure).

P.S. I was about to submit this when I thought I could try it out. I created this example project: https://github.com/saltycrane/redux-pack-example After dispatching an action, I see 2 renders when using redux-thunk and 2 renders when using redux-pack. This makes me think redux-pack does not address the issues in the above quote. Please let me know if I'm misunderstanding.

**Comment by lelandrichardson** [comment]
@saltycrane redux-pack will dispatch 2 actions for every promise. once at the start of the promise, and another when it resolves or rejects.  You can use redux-thunk to do exactly this. The problem that redux-pack is addressing is that *redux-thunk gives you the power to do a lot more*, where-as redux-pack is intentionally limiting (making it easier to do the right thing, and harder to do the wrong thing).

Does that make sense?

**Comment by saltycrane** [comment]
Thanks for your response!

Yes that makes sense. Limits are good. Thank you for clarifying!
