### ISSUE TITLE
Isn't violating this another redux pattern of how to use the reducer?

### ISSUE THREAD

**Issue by fkrauthan** [lelandrichardson/redux-pack#33]
I thought that one of the big things that redux points out is that you are not doing any logic in your reducer. With adding now `handle` into your reducer you all the sudden have "complex" calculation logic. E.g. how to handle errors, how to convert error messages, how to map responses, etc.

Another big open question to me would be how to handle data normalisation as this seems to be the way to go for bigger and more complex applications.

Looking forward to hear your thoughts on this.

**Comment by lelandrichardson** [comment]
> ...you are not doing any logic in your reducer...

I'm not sure if I'm familiar with this as a principle of redux?  If it is, I certainly question it.

> Another big open question to me would be how to handle data normalisation as this seems to be the way to go for bigger and more complex applications.

I agree this is an important question, but the challenges there I think are somewhat orthogonal to what redux-pack offers. I'm actually working on another project: https://github.com/lelandrichardson/redux-entity which *does* attempt to answer this question, although it is very much a WIP and not even published to NPM (will probably be renamed).

**Comment by fkrauthan** [comment]
Ah I see. Actual after rethinking the first thing is not really an issue as your helper still behaves correct. For any given output it will always provide a given output.

But the second question would be more important to answer I guess.
