### ISSUE TITLE
Conflicts with react-redux-toastr

### ISSUE THREAD

**Issue by rockchalkwushock** [lelandrichardson/redux-pack#36]
**Disclaimer**: I don't fully understand all the in's & out's of npm modules just FYI.

When using `redux-pack` in a current project I added the `react-redux-toatr` package and was met with the following error message on the next hot load from `webpack-dev-server`:

![missing-index](https://cloud.githubusercontent.com/assets/19720404/21743584/b26e28b6-d4ca-11e6-936d-c83625f40948.png)

Did a little investigation and it seems that both packages run on different versions of `uuid` and that is what causes the conflict. I don't know if they are _peer-dependencies_ or _dependencies_ not sure how that all works. Below are a few screenshots of installing both packages and what happens to the `uuid` directory:

![pack-install](https://cloud.githubusercontent.com/assets/19720404/21743593/fb3b5370-d4ca-11e6-97d3-4ca61e785f90.png)
![uuid-pack](https://cloud.githubusercontent.com/assets/19720404/21743594/fd39f0c8-d4ca-11e6-8d21-a1b3cb5b24ba.png)

I have looked into the _incorrect peer-dependency_ and it did not make a difference.

![toastr-install](https://cloud.githubusercontent.com/assets/19720404/21743596/ff75847e-d4ca-11e6-9786-4e224770b8f5.png)
![uuid-toatsr](https://cloud.githubusercontent.com/assets/19720404/21743597/0189edcc-d4cb-11e6-83ca-499e70b0f19d.png)

I've never run into an issue like this before. Do I open the issue with the `react-redux-toastr` dev-team as well?

**Comment by lelandrichardson** [comment]
hmm. This is strange, as normally two dependencies needing a different version of `uuid` would be fine, it would just download both of them. I'm not sure what's going on here.

Do you think you could try installing them with `npm` instead of `yarn` and let me know if it makes any difference?

**Comment by rockchalkwushock** [comment]
Used `npm install` and there were no conflicts so I'm guessing that `yarn` is locking in the dependencies for both packages and since it is seeing a conflict in version types for `uuid` it overwrites to whatever the most recent install depends on. Strange. I have not implemented the _toastr_ yet but the packages did not conflict and cause the dev-server to break. Thanks for the advice if any errors show up stemming from the same issue I'll be sure to reopen the issue.

**Comment by lelandrichardson** [comment]
@rockchalkwushock could it be a webpack issue? i'm not really sure i understand what's happening and what npm/yarn would change.

Are you using https://github.com/Urthen/case-sensitive-paths-webpack-plugin?

cc @kittens @cpojer in case it is actually a yarn issue.

**Comment by rockchalkwushock** [comment]
@lelandrichardson 

I am using `create-react-app` for the front-end so perhaps it is a conflict issue with `react-scripts`? I'm not sure how FB built the webpack in the scripts but I know it's there. So in short could be a webpack issue, but I have no webpack configs to look at in my code.

**Comment by cpojer** [comment]
@lelandrichardson if it's a Yarn issue, please bring it up on our issue tracker.

**Comment by lelandrichardson** [comment]
@rockchalkwushock so to clarify, this error is only happening on the first hot-module reload in CRA? Not initial page load?

**Comment by rockchalkwushock** [comment]
@lelandrichardson 

Sorry been a busy Sunday adulting and not coding like I would have rather been doing. 

So I cloned the last repo prior to installing `redux-pack` and `react-redux-toastr` via `npm` instead of `yarn`. I did this because after running `npm uninstall --save redux-pack react-redux-toastr` and adding both via `yarn` I was unable to replicate the problem, _maybe this points to it being a yarn issue?_

The cloned repo already had `redux-pack` added via `yarn` so I added `react-redux-toastr` via `yarn` while my project was running. The installation does not break the dev-server; however, as soon as I added the `toastrReducer` and saved the file I was presented with the error message from before:

![screen shot 2017-01-08 at 7 04 07 pm](https://cloud.githubusercontent.com/assets/19720404/21755194/4e43f260-d5d5-11e6-8902-27542a780d0e.png)

After seeing your comment about the `case-sensitive-path-webpack-plugin` (wow that's a mouthful!) and seeing the error message it seems that is the issue. I need to research how to implement that with CRA since I have no _webpack.config_ to insert a plugin.

Still doesn't answer the fact that after:

1.`npm install --save redux-pack react-redux-toastr`
2.`npm uninstall --save redux-pack react-redux-toastr`
3.`yarn add redux-pack react-redux-toastr`

The project runs without this error message.

I went ahead and performed a `yarn remove <both packages>`. My yarn.lock shows many lines of code removed and `uuid` is set to:

```plaintext
uuid@^3.0.0:
  version "3.0.1"
  resolved "https://registry.yarnpkg.com/uuid/-/uuid-3.0.1.tgz#6544bba2dfda8c1cf17e629a3a305e2bb1fee6c1"
```
I'm met with a lot of errors then obviously because those packages no longer exist.

I then ran `npm install --save <both packages>` and the application runs with no errors in Chrome or Terminal.

I then ran `npm uninstall --save <both packages>`

# Found it!

So upon `npm install --save <both packages>` the `case-sensitive-path-webpack-plugin` is installed in the `node_modules/` and since `npm uninstall --save <both packages>` does not specify that package it remains in the `node_modules/`. Then running `yarn add <both packages>` everything work with no issues.

**Resolution**: I'm not sure at all.

 Is it a `yarn` issue that this plugin should be installed? It's not a dependency to either package, but is obviously needed for an ecosystem using CRA (haven't tested in a non-CRA ecosystem so it's possibly just needed regardless because of `webpack`). Running `npm` brought the plugin into the project. I'm honestly way over my head at this point with not knowing much about npm package & yarn ecosystems.

My hope is this helps provide some clarification so either an issue (is there one?) can be fixed by (whoever would fix something like this) or we all an rejoice in the fact I am still a noob at this and it was my error! Cheers, I'm having a beer now!

**Comment by lelandrichardson** [comment]
@rockchalkwushock I believe create-react-app is installing that webpack plugin. The only reason i mentioned it was because it was in the error message that you screenshotted in the first post of this issue.

It seems like everything works, at least if you install via `npm`. I wonder if a fresh CRA project would have issues if you `yarn add`ed these two modules?

**Comment by rockchalkwushock** [comment]
@lelandrichardson 

Made a quick project to test that out. Really strange, CRA does install that dependency to `node_modules/` on the `create-react-app <project name>`. 

Now I'm left wondering how it got removed to cause this headache. Thanks for helping troubleshoot the issue and sorry if I alarmed people to their being an issue with `redux-pack` or `yarn`.
