### ISSUE TITLE
module not found

### ISSUE THREAD

**Issue by stunaz** [lelandrichardson/redux-pack#4]
How to import the middleware via nom ?
looks like there is an issue in your `package.json` file at 
```json
"main": "lib/index.js"

**Comment by lelandrichardson** [comment]
@stunaz can you show me the code you are trying to use to add the middleware?

I should put up an example in the readme for this...  something like this should work:

```
import { createStore, applyMiddleware, compose } from 'redux';
import thunk from 'redux-thunk';
import pack from 'redux-pack';

const middlewares = [
  thunk,
  pack.middleware,
];

const store = createStore(reducer, applyMiddleware(...middlewares));
```

**Comment by kyleshevlin** [comment]
I am also getting an error that says: `Module not found: Error: Cannot resolve module 'redux-pack'` I've gotten this trying to use both:

```
import { handle } from 'redux-pack'
```
and:
```
import pack from 'redux-pack'
```
What else can I give you to help out?

**Comment by kyleshevlin** [comment]
Think I figured it out. Your `package.json` says `lib`, your directory is named `src`.

**Comment by kyleshevlin** [comment]
Damn, not reading closely enough, I see in your `build` step, you have the output directory of `lib`. Sorry for the many comments.

**Comment by lelandrichardson** [comment]
ohhh. are you pulling it locally?  You would have to run `npm run build` in that case

**Comment by kyleshevlin** [comment]
I am not trying to run it locally. I used yarn to pull it into a project, attempted to import it into a few files to verify what @stunaz was seeing.

**Comment by lelandrichardson** [comment]
you're right. `.gitignore` accidentally was setup to not publish the `lib` directory. please upgrade to `0.1.1` and let me know if it's fixed!  Thanks.

**Comment by kyleshevlin** [comment]
Solved it for me.

**Comment by stunaz** [comment]
solved too 👍 
thanks
