### ISSUE TITLE
How does the library avoid triggering multiple dispatches?

### ISSUE THREAD

**Issue by khaledosman** [lelandrichardson/redux-pack#55]
Hi,

I was wondering how redux-pack avoids multiple dispatches / re-renders on async actions.. In the read me comparison with redux-thunk it says 

> This can be problematic because we are treating several dispatches as all part of a single transaction, but in reality, each dispatch causes a separate rerender of the entire component tree, where we not only pay a huge performance penalty, but also risk the redux store being in an inconsistent state.

How is that the case if its still needs to update the state in the different lifecycles of the promise allowing the components to update accordingly as shown in the example code ?

> case LOAD_FOO:
      return handle(state, action, {
        start: prevState => ({
          ...prevState,
          isLoading: true,
          fooError: null
        }),
        finish: prevState => ({ ...prevState, isLoading: false }),
        failure: prevState => ({ ...prevState, fooError: payload }),
        success: prevState => ({ ...prevState, foo: payload }),
      });

Thanks

**Comment by khaledosman** [comment]
nevermind found the answer here https://github.com/lelandrichardson/redux-pack/issues/31 , looks like it still triggers multiple dispatches, but just limits the possibility of the developer triggering more dispatches than needed.

**Comment by woolfi182** [comment]
I think you should close the issue
