### ISSUE TITLE
Willing to take a PR to add TypeScript types?

### ISSUE THREAD

**Issue by tansongyang** [lelandrichardson/redux-pack#56]
This project looks very interesting, and I'd like to try it out with TypeScript. However, there are currently no official types available.

There are two ways to do this.
1. Publish types to [DefinitelyTyped](https://github.com/DefinitelyTyped/DefinitelyTyped).
2. Include types with this [package](https://www.typescriptlang.org/docs/handbook/declaration-files/publishing.html).

Including types with this package would involve adding a `types` directory and modifying the `package.json`.

Would you take a PR adding types to this package?

**Comment by danielmhanover** [comment]
+1

**Comment by tansongyang** [comment]
Since it's been over a week, I decided to go ahead and publish to DT. There is an outstanding pull request [here](https://github.com/DefinitelyTyped/DefinitelyTyped/pull/19123).

@danielmhanover Please let me know if there are any issues, or make pull requests yourself.

If it's ever decided to include types with this package directly, we can just add here and remove from DT.

**Comment by danielmhanover** [comment]
Will do!

**Comment by cruzj6** [comment]
+1 to this also

**Comment by leandrotk** [comment]
@tansongyang, I added a PR to fix a typo. I got this while testing my reducers with redux-pack. I don't how the process works in the DT repository, but it would be great to fix it and update it in the projects.

**Comment by ljharb** [comment]
DT is the proper place for types for packages not natively authored in TS.
