### ISSUE TITLE
react-native preset

### ISSUE THREAD

**Issue by AvraamMavridis** [lelandrichardson/redux-pack#63]
Hi and thank you for this project.

I have a question, what is the reason of using the `react-native` preset?

I am trying to use this package in a react web app, and I am getting 

`Error: Couldn't find preset "react-native" relative to directory "/Users/amavridis/document/app/node_modules/redux-pack"`

Any idea?

**Comment by cruzj6** [comment]
This means you are most likely trying to babelify your node_modules, which should already be babelified. You should ignore them in your webpack config if you are using webpack.
```
{
     test: /\.(js|jsx)$/,
     exclude: /node_modules/
}
```

**Comment by devdigital** [comment]
I'm seeing this with parcel, seems related to https://github.com/parcel-bundler/parcel/issues/482
