### ISSUE TITLE
Pass the whole action into the handlers

### ISSUE THREAD

**Issue by icambron** [lelandrichardson/redux-pack#66]
One problem I'm having is that I can't pass any extra context into the handlers because the rest of the action is stripped away. For example, let's say I have a search:

```js
export const search = keyword => ({
  type: "SEARCH",
  keyword,
  promise: makeSomeAPICall(keyword)
});
```

I'm putting `keyword` in the actual action because I want access to it at the `start` phase of my handler (e.g. to show some UI about it). But as far as I can tell, I don't have access to properties like that in my reducer, because pack isn't doing either of these: a) passing the original action's fields into `dispatch` or b) passing the original action's fields into the event hooks.

**Comment by jorbascrumps** [comment]
@icambron You can pass arbitrary data with the `meta` field:

```js
export const search = keyword => ({
  type: "SEARCH",
  promise: makeSomeAPICall(keyword),
  meta: {
    keyword
  }
});
```

You can then grab the action (containing the `meta` data) as the second argument in your handler.

**Comment by icambron** [comment]
@iamchristopher I ended up doing just that after reading more code. It didn't strike me that that it was intended for that, though. Is it?
