### ISSUE TITLE
__DEV__ is not defined

### ISSUE THREAD

**Issue by stunaz** [lelandrichardson/redux-pack#7]
<img width="442" alt="screen shot 2016-12-14 at 7 43 09 pm" src="https://cloud.githubusercontent.com/assets/1305483/21207331/af851440-c235-11e6-9d40-169e9b9ed456.png">

`__DEV__` not defined on [https://github.com/lelandrichardson/redux-pack/blob/master/src/handle.js#L45](url)

**Comment by lelandrichardson** [comment]
hmm. this is definitely a problem.

I'm thinking I will change this to `process.env.NODE_ENV === 'development'`. Thoughts?

**Comment by stunaz** [comment]
or `process.env.NODE_ENV !== 'production'`

**Comment by lelandrichardson** [comment]
@stunaz yeah, i'm torn on this. I'd like this library to provide helpful warnings which can make the dev experience much better... I think other libraries leverage `process.env.NODE_ENV`...

**Comment by stunaz** [comment]
go for it 👍
