### ISSUE TITLE
Continuing this project

### ISSUE THREAD

**Issue by Robertmw** [lelandrichardson/redux-pack#73]
Hi guys, I have made a copy of this repo (and package) where I updated the dependencies. If you want to contribute to it with other changes you are more than welcome!

For the owners of this project, if you're not ok with this please email me and I'm gonna take it down.

Forked repo: https://github.com/Robertmw/redux-pack
NPM module: https://www.npmjs.com/package/redux-pack-updated

**Comment by ljharb** [comment]
Why? Is there an open PR for that that’s not merged?

It’s fine to fork but it’s usually unnecessary.

**Comment by Robertmw** [comment]
I saw that the last change was on 25 Mar 2017. If you are the new maintainer i guess i can remove the module and create a PR with my changes here.

**Comment by ljharb** [comment]
There's a number of maintainers; the first step is always to file an issue and/or PR :-)

**Comment by Robertmw** [comment]
Done -> https://github.com/lelandrichardson/redux-pack/pull/74

I will remove the updated package from NPM once this is merged.
